# Generated by Django 4.2.4 on 2023-08-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ventes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_clients', models.PositiveIntegerField()),
                ('total_factures', models.PositiveIntegerField()),
                ('total_montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Statistiques',
            },
        ),
    ]
