# Generated by Django 4.2.4 on 2023-08-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0002_statistique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='total_ventes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
