# Generated by Django 4.2.4 on 2023-08-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0003_alter_statistique_total_ventes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='total_clients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_factures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
