# Generated by Django 4.2.4 on 2023-08-30 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0004_alter_statistique_total_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='datecreation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
