# Generated by Django 4.2.4 on 2023-08-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0005_client_datecreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adressefacturation',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
