# Generated by Django 4.2.4 on 2023-08-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0006_client_adressefacturation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adressefacturation',
        ),
    ]
