# Generated by Django 4.2.4 on 2023-08-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0007_remove_client_adressefacturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adressefacturation',
            field=models.CharField(default='Votre adresse', max_length=300),
        ),
    ]
