# Generated by Django 4.2.4 on 2023-08-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0008_client_adressefacturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
