# Generated by Django 4.2.4 on 2023-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0011_alter_facture_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='frais_liv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
