# Generated by Django 4.2.4 on 2023-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0012_facture_frais_liv_facture_montant_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_restant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
