# Generated by Django 4.2.4 on 2023-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0014_alter_facture_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montant_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
