# Generated by Django 4.2.4 on 2023-09-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0017_alter_facture_total_alter_facture_montant_restant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montant_restant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
