# Generated by Django 4.2.4 on 2023-09-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0020_alter_facture_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_restant',
        ),
    ]
