# Generated by Django 4.2.4 on 2023-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0021_remove_facture_montant_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='rest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
