# Generated by Django 4.2.4 on 2023-09-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0022_facture_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='adresseemission',
            field=models.CharField(default='Votre adresse', max_length=300),
        ),
    ]
