# Generated by Django 4.2.4 on 2023-09-04 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0023_facture_adresseemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reference',
            field=models.CharField(default='la réference', max_length=100),
        ),
        migrations.AddField(
            model_name='devis',
            name='Tot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='datecreation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='facture',
            name='datecreation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
