# Generated by Django 4.2.4 on 2023-09-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0024_article_reference_devis_tot_devis_datecreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gesfact.client'),
        ),
    ]
