# Generated by Django 4.2.4 on 2023-09-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0025_alter_devis_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devis',
        ),
    ]
