# Generated by Django 4.2.4 on 2023-09-22 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0026_delete_devis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreation', models.DateField(default=django.utils.timezone.now)),
                ('numero_devis', models.CharField(max_length=50)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('quantite', models.PositiveIntegerField()),
                ('serie', models.CharField(max_length=50)),
                ('Tot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='devis/pdfs/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gesfact.article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gesfact.client')),
            ],
        ),
    ]
