# Generated by Django 4.2.4 on 2023-09-22 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0027_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='datecreation',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
