# Generated by Django 4.2.4 on 2023-09-23 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gesfact', '0028_alter_devis_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='datecreation',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
